# Generated by Django 5.2.5 on 2026-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seed_opening_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not selected yet'), ('card', 'Bank Card'), ('transfer', 'Bank Transfer'), ('other', 'Other Payment Option')], default='', max_length=20),
        ),
    ]
